### PR TITLE
Update on the Contributors List Action

### PR DESCRIPTION
**Pull request by u-siri-ous**
I found a similar Action, but maybe more complete, as it adds the name or username of the contributor as a URL and does not create an SVG.
This is the documentation about it, https://github.com/marketplace/actions/contribute-list

### CODE REVIEW

**Comment by iacopomasi** [comment]
Dear @u-siri-ous,

thank you for this update. I also saw this other github action before.  I saw in your version of the website that we can link to the username but squared icons. Esthetically I prefer the graphics of the SVG with rounded avatars but here the link it is a plus. So I am undecided. Do you think this is better? Regardless, thank you again

**Comment by u-siri-ous** [comment]
Good afternoon professor,
I made the PR because I saw that the SVG Contributors List Github action wasn't working correctly some days ago, as some of the contributors were not showing in the SVG. 
I agree that the rounded version does look better though, moreover, the second version creates clutter in the .md files.

The problem is that the new execution of the action somehow cancelled the correct SVG and substituted it with a new but wrong-generated SVG. This happened a few days ago, solved itself, and has happened again now.
This is visible from commit c1d013c, which triggered the action and generated bot-commit 383cda3.

I think it can be solved by scheduling the action, or we can try and see if it sorts itself out at the next push, as it did before.

Thank you for your time.

**Comment by iacopomasi** [comment]
Dear @u-siri-ous ,

Thank you for investigating this. I saw that now that I made some push,the SVG updated once again and I see new faces in the contrib list. For now we will stick to this but you can try in your fork to see if you can set 1) rounded avatars 2) remove the border in the tables with the new github action. This is not urgent and please priority studying for the exam to this. 

What you could try is to write to https://github.com/wow-actions/contributors-list/issues/6  and say also that we are getting the issue (this is less work). 

thank you

**Comment by u-siri-ous** [comment]
Good morning professor,
I'm glad the problem has been solved for now. The creator of the action was notified when I mentioned the issue in this PR, I will keep an eye on the issue and let you know.

In the meantime, if you don't mind, I would like to close this PR and open another one when I work on the fixes.

Thank you for your time.

**Pull request closed without merging**
